title: Miguel Marcelino
email: mac.marcelino@outlook.pt
baseurl: "" # the subpath of your site, e.g. /blog
url: "MiguelMarcelino.github.io"
github_username:  MiguelMarcelino

# Build settings
remote_theme: jekyll/minima
minima:
  skin: dark

plugins:
  - jekyll-feed
