title: Miguel Marcelino
email: mac.marcelino@outlook.pt
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://somnyst.com"
github_username:  MiguelMarcelino

# Build settings
theme: minima
plugins:
  - jekyll-feed
