title: Miguel Marcelino
email: mac.marcelino@outlook.pt
description: >- # this means to ignore newlines until "baseurl:"
  A website to publish all kinds of articles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://somnyst.com"
github_username:  MiguelMarcelino

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
